-- Arquivo: schema.sql
-- Instrução: Importar diretamente no SQL Editor do Supabase

-- 1. Tabela de Jornadas e Tolerâncias por Cargo
CREATE TABLE jornadas_trabalho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo VARCHAR(50) NOT NULL, -- 'PIZZAIOLO', 'ENTREGADOR', 'CAIXA', 'ATENDENTE'
    horario_entrada TIME NOT NULL,
    horario_saida TIME NOT NULL,
    tolerancia_entrada_minutos INT NOT NULL DEFAULT 10,
    tolerancia_saida_minutos INT NOT NULL DEFAULT 10,
    exige_fechamento_caixa BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Tabela de Funcionários
CREATE TABLE funcionarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula VARCHAR(20) UNIQUE NOT NULL,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    jornada_id BIGINT REFERENCES jornadas_trabalho(id),
    hash_reconhecimento_facial TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Tabela de Registros de Ponto
CREATE TABLE registros_ponto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id BIGINT REFERENCES funcionarios(id) NOT NULL,
    data_hora_registro TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    data_referencia_turno DATE NOT NULL,
    tipo_registro VARCHAR(20) CHECK (tipo_registro IN ('ENTRADA', 'SAIDA_ALMOCO', 'RETORNO_ALMOCO', 'SAIDA')) NOT NULL,
    hash_comprovante VARCHAR(64) UNIQUE NOT NULL,
    ip_origem VARCHAR(45),
    latitude NUMERIC(10, 8),
    longitude NUMERIC(11, 8),
    saida_emergencia BOOLEAN DEFAULT FALSE
);

-- 4. Tabela de Ocorrências e Justificativas
CREATE TABLE ocorrencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id BIGINT REFERENCES funcionarios(id) NOT NULL,
    data_referencia DATE NOT NULL,
    tipo_ocorrencia VARCHAR(30) CHECK (
        tipo_ocorrencia IN ('ATRASO', 'ATRASO_CRITICO', 'SAIDA_ANTECIPADA', 'FALTA_INJUSTIFICADA', 'FALTA_JUSTIFICADA', 'HORA_EXTRA_ENTREGA')
    ) NOT NULL,
    minutos_excedentes INT DEFAULT 0,
    status_aprovacao VARCHAR(20) DEFAULT 'PENDENTE' CHECK (status_aprovacao IN ('PENDENTE', 'APROVADO', 'REJEITADO')),
    justificativa TEXT,
    url_documento_comprovante TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);