-- Arquivo: schema.sql
-- Instrução: Importar diretamente no SQL Editor do Supabase

-- 1. Tabela de Jornadas e Tolerâncias por Cargo
CREATE TABLE IF NOT EXISTS jornadas_trabalho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo VARCHAR(50) NOT NULL UNIQUE, -- 'PIZZAIOLO', 'ENTREGADOR', 'CAIXA', 'ATENDENTE'
    horario_entrada TIME NOT NULL,
    horario_saida TIME NOT NULL,
    tolerancia_entrada_minutos INT NOT NULL DEFAULT 10,
    tolerancia_saida_minutos INT NOT NULL DEFAULT 10,
    exige_fechamento_caixa BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Tabela de Funcionários
CREATE TABLE IF NOT EXISTS funcionarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula VARCHAR(20) UNIQUE NOT NULL,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) UNIQUE NOT NULL,
    jornada_id BIGINT REFERENCES jornadas_trabalho(id),
    hash_reconhecimento_facial TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Tabela de Control de Caixa (para validação do perfil Caixa e Atendimento)
CREATE TABLE IF NOT EXISTS status_caixa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_operacao DATE NOT NULL DEFAULT CURRENT_DATE UNIQUE,
    fechado BOOLEAN NOT NULL DEFAULT FALSE,
    fechado_por_funcionario_id BIGINT REFERENCES funcionarios(id),
    fechado_em TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 4. Tabela de Pedidos em Rota de Entrega (para regra de HORA_EXTRA_ENTREGA)
CREATE TABLE IF NOT EXISTS entregas_em_andamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id BIGINT REFERENCES funcionarios(id) NOT NULL,
    status VARCHAR(20) DEFAULT 'EM_ROTA' CHECK (status IN ('EM_ROTA', 'CONCLUIDA')),
    iniciado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    concluido_em TIMESTAMP WITH TIME ZONE
);

-- 5. Tabela de Registros de Ponto
CREATE TABLE IF NOT EXISTS registros_ponto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id BIGINT REFERENCES funcionarios(id) NOT NULL,
    data_hora_registro TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    data_referencia_turno DATE NOT NULL,
    tipo_registro VARCHAR(20) CHECK (tipo_registro IN ('ENTRADA', 'SAIDA_ALMOCO', 'RETORNO_ALMOCO', 'SAIDA')) NOT NULL,
    hash_comprovante VARCHAR(64) UNIQUE NOT NULL,
    ip_origem VARCHAR(45),
    latitude NUMERIC(10, 8),
    longitude NUMERIC(11, 8),
    saida_emergencia BOOLEAN DEFAULT FALSE,
    foto_verificacao_url TEXT
);

-- 6. Tabela de Ocorrências e Justificativas
CREATE TABLE IF NOT EXISTS ocorrencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id BIGINT REFERENCES funcionarios(id) NOT NULL,
    data_referencia DATE NOT NULL,
    tipo_ocorrencia VARCHAR(30) CHECK (
        tipo_ocorrencia IN ('ATRASO', 'ATRASO_CRITICO', 'SAIDA_ANTECIPADA', 'FALTA_INJUSTIFICADA', 'FALTA_JUSTIFICADA', 'HORA_EXTRA_ENTREGA', 'SAIDA_FORCADA_EMERGENCIA')
    ) NOT NULL,
    minutos_excedentes INT DEFAULT 0,
    status_aprovacao VARCHAR(20) DEFAULT 'PENDENTE' CHECK (status_aprovacao IN ('PENDENTE', 'APROVADO', 'REJEITADO')),
    justificativa TEXT,
    url_documento_comprovante TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- DADOS DE SEED (CARGOS, JORNADAS E FUNCIONÁRIOS MOCK)
INSERT INTO jornadas_trabalho (cargo, horario_entrada, horario_saida, tolerancia_entrada_minutos, tolerancia_saida_minutos, exige_fechamento_caixa)
VALUES
    ('PIZZAIOLO', '17:00:00', '01:00:00', 5, 10, FALSE),
    ('ENTREGADOR', '18:00:00', '23:30:00', 10, 30, FALSE),
    ('CAIXA', '16:30:00', '00:30:00', 10, 10, TRUE),
    ('ATENDENTE', '17:00:00', '00:00:00', 10, 10, TRUE)
ON CONFLICT (cargo) DO NOTHING;

INSERT INTO funcionarios (matricula, nome, cpf, jornada_id, ativo)
VALUES
    ('FUNC001', 'Mario Pizzaiolo', '11122233344', 1, TRUE),
    ('FUNC002', 'Carlos Motoboy', '22233344455', 2, TRUE),
    ('FUNC003', 'Ana Caixa', '33344455566', 3, TRUE),
    ('FUNC004', 'Beatriz Atendente', '44455566677', 4, TRUE)
ON CONFLICT (matricula) DO NOTHING;

INSERT INTO status_caixa (data_operacao, fechado)
VALUES (CURRENT_DATE, FALSE)
ON CONFLICT (data_operacao) DO NOTHING;
